name: How to Build a Portfolio on Github
markdown: kramdown
kramdown:
  parse_block_html: true
pygments: true
baseurl: /github-for-portfolios
safe: false
lsi: false
pygments: true
permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

assets:
  baseurl: /github-for-portfolios/assets
  css_compressor: sass
